### ISSUE TITLE
Suggestion: Adding character data type with ascii comparison or other method to validate alphabet of string

### ISSUE THREAD

**Issue by Zeronfinity** [FurqanSoftware/scanlib#1]
Suppose I want to validate that each character of a string is an uppercase Latin alphabet letter.

But I am not sure if this is possible with current features of scanlib.

Maybe something like the following would be useful in such case.

```
var S string
scan S
check 1 <= len(S), len(S) <= 50000
eol

for i := 0 ... len(S)
    check 'A' <= S[i], S[i] <= 'Z'
```

**Comment by hjr265** [comment]
Re: adding support for character data type, that is an excellent suggestion! I might have to split it into two types: byte and rune (taking inspiration from Go) to accommodate proper support for Unicode characters. 

About the specific case of validation that you have used as an example, this can be done already using the `re` function:

```
re(s, x): Returns true if string s matches regular expression x.
```

Something like this could work for your case:

```
var S string
scan S
check len(S) >= 1, len(S) <= 50000, re(S, "^[A-Z]+$")
eol
eof
```

**Comment by hjr265** [comment]
@Zeronfinity Adding support for character data type is an excellent suggestion! I might have to split it into two types: byte and rune (taking inspiration from Go) to accommodate proper support for Unicode characters. 

About the specific case of validation that you have used as an example, this can be done already using the `re` function:

```
re(s, x): Returns true if string s matches regular expression x.
```

Something like this could work for your case:

```
var S string
scan S
check len(S) >= 1, len(S) <= 50000, re(S, "^[A-Z]+$")
eol
eof
```

**Comment by Zeronfinity** [comment]
Oh, I see.

I had missed the regex function while reading the documentation, my bad.
