### ISSUE TITLE
Checking space formatting of input

### ISSUE THREAD

**Issue by Zeronfinity** [FurqanSoftware/scanlib#2]
Suppose problem statement says an array is given input as N space-separated integers in a single line.

Any suggestion on how we can check if test cases strictly follow such claim?

Mainly, I want to check if there is a single space between two integers, no space at start or end of the array, all integers are in a single line etc.

One way for doing this currently is taking the whole line input as a string and parse the integers from their manually (provided each character in the string can be accessed separately). We can then use regex on the string to check the space formatting and such.

If something like sscanf or stringstream from C/C++ is supported, then it would be much easier as the parsing from string would not need manual handling then while we can still use the regex on the string.

**Comment by hjr265** [comment]
@Zeronfinity 

The `scan` keyword is very particular about spacing. It will skip at most one space character (ASCII 32) when reading the next token from the input stream.

Take this scanspec for example:

```
var N int
scan N
eol
var A [N]int
for i := 0 ... N
	scan A[i]
end
eol
eof
```

This scanspec will yield an error if the N integers are not on the same line each separated by exactly one space.

The following input will pass:

```
5
1 2 3 4 5
```

But these inputs will yield errors:

```
5
1  2 3 4 5
```

`parse error (cursor 2:3): want int, got " "`

```
5
1
2
3
4
5
```

`parse error (cursor 3:0): want int, got "\n"`

Except this input, which is a known issue:

```
5
 1 2 3 4 5
```

(This should yield an error, but the current logic of skipping spaces treats the leading space as something it can skip.)

`scan`'s logic is that it will expect the next token to be on the same line. Only after `eol` will `scan` read from the next line.

**Comment by Zeronfinity** [comment]
I see. That handles the issue then.

**Comment by hjr265** [comment]
@Zeronfinity Right. Plus I have just made [this change](https://github.com/FurqanSoftware/scanlib/commit/7be26d1aa03dec50368e079aef1778fb26f1f99d) that fixes the issue I mentioned earlier. Line prefix spaces are not skipped anymore. [These tests](https://github.com/FurqanSoftware/scanlib/tree/master/testdata/arrayline) cover these scenarios.

_Note that this change has been made to Scanlib package. I will be updating Scanlib in Drafts and Toph later today or tomorrow in sha Allah._
